### ISSUE TITLE
Issue with GHC LANGUAGE pragmas

### ISSUE THREAD

**Issue by j-walk** [metakirby5/codi.vim#11]
Haskell language pragmas (GADTs, UnicodeSyntax, etc) aren't functioning.

http://i.imgur.com/xGbqJyo.png

**Comment by metakirby5** [comment]
Can you confirm that this also works in GHCI? Codi does not support anything beyond what the underlying interpreter supports.

Also, for further investigation, could you paste exactly what you entered into Codi here? I just want to make sure I'm entering the right Unicode characters.

**Comment by dkasak** [comment]
@metakirby5 ghci doesn't support that syntax, it only works in source files. Also, top-level definitions (using the equality sign) in source code work differently than assignments in ghci so just passing every line of source code isn't going to work properly for Haskell.

That said, I'm not even sure that's the goal of this project. It seems like your intent with codi was more along the lines of an easily editable interactive session rather than a live evaluator of the source language. For Python these two things are roughly the same so it works out, but this isn't true for ghci/Haskell.

**Comment by metakirby5** [comment]
@dkasak You are spot-on regarding the goal of this project. It's essentially meant to be just like using the interpreter for trying out small snippets of code, but a bit handier. I'll add a note about that to the documentation - thanks!
