### ISSUE TITLE
Simply doesn't work with ruby

### ISSUE THREAD

**Issue by hrqmonteiro** [metakirby5/codi.vim#133]
It worked with all of the languages i've tested, but non on Ruby. How could i fix this?

I have ruby, irb and all of it properly installed.

**Comment by metakirby5** [comment]
Can you give some more details? Any error messages, logs, etc?

**Comment by hrqmonteiro** [comment]
How can i see some log? On the regular nvim log it doesn't appear anything related.

**Comment by metakirby5** [comment]
Please refer to the [documentation](https://github.com/metakirby5/codi.vim/blob/master/doc/codi.txt#L320):

```
                                                                  *g:codi#log*
g:codi#log
             Path to the file where Codi logs information. This can be useful
             for debugging (e.g. |codi-interpreters-preprocess|) and when
             fixing or submitting issues.

             Default value is '', which disbles all logging.
```

**Comment by mracos** [comment]
Ruby wouldn't work at all for me too and after some time debugging I think I found out why. It seems that since ruby 2.7 `irb` supports [multiline editing](https://blog.saeloun.com/2019/09/23/new-irb-features.html#introduce-multiline-mode-by-reline), but _apparently_ codi.vim does not like that.

I just added `--nomultiline` to ruby's `bin` value and it worked. Not sure if is the same case but no trouble trying right?

https://github.com/metakirby5/codi.vim/blob/cf62681a4962ce1873e4b2a5e0bf401dcd42890f/autoload/codi/load.vim#L150

Maybe there is something in codi.vim that we can change to support multiline and drop this hack but I'll be honest that I have not dig that deep, for now the hack works for me. 😄
