### ISSUE TITLE
Partial output

### ISSUE THREAD

**Issue by Flamme13** [metakirby5/codi.vim#141]
How I can fix the output of the array or object.

Now I have output only the last line.

![Selection_017](https://user-images.githubusercontent.com/8742198/144761264-c7194c11-37b9-431d-ac36-e6462efc9585.png)

I tried to disable virtual text but it did not help.

## Environment
- Operating system (Ubuntu 20.04)
- Version of `script` (if you don't know, just paste the last line of the man page - vim:ft=help:tw=78:sw=13:norl:)
- vim --version (NVIM v0.6.0)

**Comment by metakirby5** [comment]
This is because the output is itself multi-line per input line. It's only possible to display up to one line of output for each line of input. If the other lines had output, there would be nowhere for the excess output to go.

![image](https://user-images.githubusercontent.com/3402603/145016639-8b223585-2ef8-406f-87ed-e208cfabb448.png)

**Comment by Flamme13** [comment]
seems like bug =(

because I can work only with simple data.

is it possible to specify multi-line output in the settings?

**Comment by metakirby5** [comment]
Codi is largely only meant for simple data, since the entire buffer is run again with every keystroke.
As mentioned before, multiple lines are not supported, because there is simply nowhere for the extra lines to go.


You may reformat multi-line output into a single line by implementing [`rephrase`](https://github.com/metakirby5/codi.vim/blob/master/doc/codi.txt#L594). For more details, please refer to the [`OUTPUT SPECIFICATION`](https://github.com/metakirby5/codi.vim/blob/master/doc/codi.txt#L483).

**Comment by Flamme13** [comment]
Thanks for the answer.
