### ISSUE TITLE
breaking up larger outputs.

### ISSUE THREAD

**Issue by Bretley** [metakirby5/codi.vim#27]
Is there a way for Codi to break a longer list up onto multiple lines? I've been using Codi with pwntools for exploitation (It's actually working fairly well!) and commonly some of the lists have 20 or so strings and it's off the screen. Thoughts?

**Comment by metakirby5** [comment]
Glad to hear you're enjoying Codi!

Unfortunately, multi-line output clashes with line-wise evaluation. It could be possible to show more output only if the corresponding lines evaluate to nothing (i.e. empty lines in the main buffer), but it would require a pretty big overhaul of the core logic. The change would be a gain in this particular use case, but would have no effect on the common use case. I would definitely like to incorporate this feature at some point in the future, though.

On another note: if you need to split up one line of output in to several, that must be handled via the preprocessor attribute. The preprocessor is a bit inflexible at the moment (only supporting line-wise pre-processing), but I have plans to allow pre-processing given the whole output.

**Comment by juliosueiras** [comment]
Hi, sorry to bother, if multiline was implemented, does that enable most interpreted language(even one that aren't like root for c) , since I try to implement Io, and Scala into codi.vim(since there is only two place require for adding a new language/interpreter), Io is working though only printing the first line, same goes for scala, my question is since multiline output on side would break the presentation , would it possible of either A) taking the multiline and output as a one long output(though it would display some items weirdly) on the side or B) take the Tagbar & Git diff approach of allowing expand and collapse on the sidebar for multiline and when expand put same amount of new line onto the buffer, when collapse vice versa

and sorry for my bad english

**Comment by metakirby5** [comment]
@juliosueiras No problem! Multi-line as one long output is currently not possible because of the line-wise nature of preprocess. It currently is this way because of how asynchronous output is buffered. I have plans for changing this behavior, but I probably won't get to implementing it for a little while since things are a bit busy for me.

Regarding the Tagbar approach, that could be a good idea. I haven't thought about incorporating folds into multi-line output, so I'll mull it over.

**Comment by vn-ki** [comment]
Can we expect this soon? This is the only thing that makes me use ipython instead of codi.

**Comment by ssh352** [comment]
it would be nice to display multi line output, I'll find another way to use vim and ipython together. @vn-ki can you suggest? Thanks!
