### ISSUE TITLE
slow evaluation for Clojure

### ISSUE THREAD

**Issue by cirqueit** [metakirby5/codi.vim#34]
Thanks for the awesome tool!

I added Clojure via `lein repl`. Works well though really slow.
 Is this to be expected?

**Comment by metakirby5** [comment]
Since Codi spins up a repl with every keystroke, the result will take as long as it takes to start the repl up and evaluate the code. Does `lein repl` take awhile normally? If so, this is expected behavior. I recommend setting `autocmd` to `CursorHold` for slower interpreters, to avoid unnecessary cycles on results you won't ever see.

BTW, feel free to contribute your Clojure configuration :) Check [this file](https://github.com/metakirby5/codi.vim/blob/master/autoload/codi/load.vim#L34) out, and ping me on Gitter or something if you need help.

**Comment by cirqueit** [comment]
Makes sense.

I went back and started experimenting.
I now have two clojure/clojurescript solutions:

 - `planck` a clojurescript command line tool / REPL which takes < 1 sec to update

- `grenchman repl` which is instant, but connects to an existing nREPL (so need to launch before / configure)

I'll make a pull request later this weekend.

**Comment by metakirby5** [comment]
The `grenchman repl` solution you propose is interesting, because this presents a good use case for #24. If you have the time, I absolutely encourage you to give it a shot - it should probably implemented as a quick system call where the return code is checked. For example, only allow clojure if grepping for the nREPL process returns 0. Let me know what you think.

**Comment by cirqueit** [comment]
Turns out I jumped the gun with `grenchman`. It's instant but doesn't support [multiline inputs](https://github.com/technomancy/grenchman/issues/16) and requires using an existing `nREPL` instance (by having a `project.clj` file and running `lein trampoline repl :headless`). Here's the relevant lines if anyone wants to experiment while I figure out what to do.

`'bin', ['grench', 'repl'],` 

`planck` on the other hand works fine, requires no config, but takes 1 sec to eval.

`'bin': ['planck', '-v', '-d'],`

The same non-greedy regex works for both solutions:

`'prompt': '^.\{-}=> ',`
